26-08',
    received_at: '2026-08-05',
    gross_amount: 250000,
    gross_currency: 'NGN',
    fees_amount: 0,
    net_amount: 250000,
    net_currency: 'NGN',
    conversion_rate: 1,
    converted_amount: 250000,
    converted_currency: 'NGN',
    status: 'VERIFIED',
    notes: 'Direct fee receipt',
    provenance: 'VERIFIED'
  }],
  cycleReconciliation: [{
    id: '1',
    source_key: 'ROYALTY_BMI',
    source_name: 'BMI',
    source_class: 'ROYALTY',
    historical_receipts_verified: true,
    historical_receipts_count: 4,
    historical_net_amount: 304.40,
    historical_net_currency: 'USD',
    cycle_model: 'QUARTERLY',
    future_cycle_measurement_status: 'PROVISIONAL',
    provenance: 'VERIFIED',
    status: 'ACTIVE'
  }, {
    id: '2',
    source_key: 'ROYALTY_SENTRIC',
    source_name: 'Sentric',
    source_class: 'ROYALTY',
    historical_receipts_verified: true,
    historical_receipts_count: 5,
    historical_net_amount: 238.10,
    historical_net_currency: 'GBP',
    cycle_model: 'QUARTERLY',
    future_cycle_measurement_status: 'PROVISIONAL',
    provenance: 'VERIFIED',
    status: 'ACTIVE'
  }],
  tradingAccounts: [{
    id: 'acc1',
    account_name: 'ACTIVE $10K GOAT FUNDED TRADER PAY LATER',
    account_type: 'PROP',
    prop_firm: 'Goat Funded Trader',
    program: 'Pay Later',
    starting_balance: 10000,
    activation_cost_usd: 118,
    activation_date: '2026-07-01',
    status: 'ACTIVE',
    funding_provenance: 'VERIFIED',
    notes: 'Primary active account'
  }],
  tradingCapitalState: [{
    id: 'cs1',
    account_id: 'acc1',
    measured_at: '2026-08-20T12:00:00Z',
    stable_equity: 10052.93,
    floating_pnl: 0,
    realized_day_pnl: -93.30,
    realized_week_pnl: -93.30,
    cumulative_realized_pnl: -93.30,
    previous_equity_high: 10222.35,
    biggest_profitable_day: 92.78,
    required_profit_pool: 463.90,
    net_profit_pool: 52.93,
    consistency_gap: 410.97,
    authorized_lot: 0.01,
    authorized_stop_points: 15,
    authorized_risk_usd: 15,
    capital_band_min: 30,
    capital_band_max: 150,
    capacity_status: 'VERIFIED_BAND',
    governance_status: 'RECONCILED_PENDING_EXECUTION_PROVENANCE'
  }],
  tradingExecutions: [{
    id: 'ex1',
    trading_date: '2026-08-19',
    event_time_ny: '09:45:00',
    session: 'LONDON',
    instrument: 'XAUUSD',
    event_type: 'ENTRY',
    direction: 'LONG',
    lot: 0.01,
    entry_price: 2485.20,
    realized_pnl_usd: null,
    risk_usd: 15,
    validation_state: 'PENDING'
  }, {
    id: 'ex2',
    trading_date: '2026-08-19',
    event_time_ny: '10:12:00',
    session: 'LONDON',
    instrument: 'XAUUSD',
    event_type: 'EXIT',
    direction: 'LONG',
    lot: 0.01,
    entry_price: 2485.20,
    exit_price: 2492.80,
    realized_pnl_usd: 7.60,
    risk_usd: 15,
    validation_state: 'SUPPORTING'
  }, {
    id: 'ex3',
    trading_date: '2026-08-20',
    event_time_ny: '08:30:00',
    session: 'LONDON',
    instrument: 'XAUUSD',
    event_type: 'STOP_OUT',
    direction: 'SHORT',
    lot: 0.01,
    entry_price: 2498.50,
    exit_price: 2513.40,
    realized_pnl_usd: -93.30,
    risk_usd: 15,
    validation_state: 'CONTRADICTORY'
  }],
  tradingObservations: [{
    id: 'obs1',
    created_at: '2026-08-18',
    title: 'London open volatility cluster',
    observation: 'XAUUSD shows elevated range in first 45m of London',
    status: 'ACTIVE',
    frequency_count: 3,
    first_observed_at: '2026-07-22',
    last_observed_at: '2026-08-18',
    state: 'CURRENT'
  }],
  tradingValidations: [{
    id: 'val1',
    created_at: '2026-08-10',
    hypothesis_id: 'h1',
    supporting_count: 5,
    contradictory_count: 2,
    persistence_rate: 0.625,
    result: 'PROVISIONAL',
    evidence_summary: 'Majority support, two contradictions under news',
    decision: 'CONTINUE_OBSERVE',
    state: 'OPEN'
  }],
  businessDomains: [{
    id: 'd1',
    domain_key: 'KVNGVIDARR_ECOSYSTEM',
    name: 'KVNGVIDARR Business Ecosystem',
    domain_type: 'ROOT',
    purpose: 'Canonical ecosystem container',
    status: 'ACTIVE',
    authority_scope: 'FULL'
  }, {
    id: 'd2',
    domain_key: 'CONTENT_BUSINESS',
    name: 'Content Business',
    domain_type: 'FUNCTION',
    purpose: 'Content production & distribution',
    status: 'ACTIVE',
    authority_scope: 'DOMAIN'
  }, {
    id: 'd3',
    domain_key: 'MARKETING_FUNCTION',
    name: 'Marketing Function',
    domain_type: 'FUNCTION',
    purpose: 'Campaigns, spend, audience growth',
    status: 'ACTIVE',
    authority_scope: 'DOMAIN'
  }, {
    id: 'd4',
    domain_key: 'MUSIC_BUSINESS',
    name: 'Music Business',
    domain_type: 'FUNCTION',
    purpose: 'Audience, retention, royalties',
    status: 'ACTIVE',
    authority_scope: 'DOMAIN'
  }],
  musicAudience: [{
    id: 'ma1',
    period_month: '2026-07',
    monthly_listeners: 633,
    active_listeners: 435,
    super_listeners: 7,
    new_listeners: 87
  }, {
    id: 'ma2',
    period_month: '2026-08',
    monthly_listeners: 518,
    active_listeners: 466,
    super_listeners: 6,
    new_listeners: null
  }],
  musicRetention: [{
    id: 'mr1',
    period_month: '2026-08',
    active_listener_contribution_pct: 94,
    previously_active_pct: 2,
    programmed_listeners_pct: 4
  }],
  contentAssets: [],
  marketingCampaigns: [],
  marketingSpend: [],
  creativeProjects: [],
  llmCapabilityRegistry: [{
    id: 'c1',
    platform: 'GROK',
    capability: 'CODE_GENERATION',
    status: 'VERIFIED-CALLABLE',
    evidence: 'Live execution confirmed',
    limitation: 'Context window limits on very large files',
    last_verified_at: '2026-08-19'
  }, {
    id: 'c2',
    platform: 'GROK',
    capability: 'WEB_SEARCH',
    status: 'VERIFIED-AVAILABLE',
    evidence: 'Tool registered',
    last_verified_at: '2026-08-19'
  }, {
    id: 'c3',
    platform: 'CLAUDE',
    capability: 'LONG_CONTEXT_ANALYSIS',
    status: 'VERIFIED-AVAILABLE',
    evidence: 'Documented + prior runs',
    limitation: 'Rate limits',
    last_verified_at: '2026-08-15'
  }, {
    id: 'c4',
    platform: 'GPT',
    capability: 'STRUCTURED_EXTRACTION',
    status: 'UNVERIFIED',
    evidence: 'Documentation only',
    last_verified_at: null
  }],
  llmMemoryProtocol: [{
    id: 'm1',
    protocol_version: '1.0',
    rule_key: 'DISTRIBUTED_OS_RECONSTRUCTION_INVARIANT',
    priority: 1,
    instruction: 'Supabase is the canonical structured-state layer. Google Workspace/Drive is the human-readable structural knowledge layer. Operational Prep contains moving/current knowledge. Structural Prep contains durable verified knowledge. Absence from one layer does not prove absence from the OS.',
    applies_to: 'ALL_NODES',
    authority_scope: 'SYSTEM',
    human_authorization_required: false,
    state: 'CURRENT',
    status: 'ACTIVE'
  }, {
    id: 'm2',
    protocol_version: '1.0',
    rule_key: 'CAPABILITY_EVIDENCE',
    priority: 2,
    instruction: 'Capability statuses must be treated as evidence-backed: VERIFIED-CALLABLE, VERIFIED-AVAILABLE, UNVERIFIED, NOT AVAILABLE.',
    applies_to: 'LLM_ROUTING',
    authority_scope: 'SYSTEM',
    human_authorization_required: false,
    state: 'CURRENT',
    status: 'ACTIVE'
  }, {
    id: 'm3',
    protocol_version: '1.0',
    rule_key: 'TIME_AUTHORITY_NEW_YORK',
    priority: 3,
    instruction: 'Session and frequency clocks use New York time as authority.',
    applies_to: 'TRADING',
    authority_scope: 'DOMAIN',
    human_authorization_required: false,
    state: 'CURRENT',
    status: 'ACTIVE'
  }, {
    id: 'm4',
    protocol_version: '1.0',
    rule_key: 'NO_PREMATURE_PROMOTION',
    priority: 4,
    instruction: 'Never silently promote observation → canonical, historical → current, projection → confirmed, documentation → verified capability, equity → liquidity, empty table → inactive domain.',
    applies_to: 'ALL',
    authority_scope: 'SYSTEM',
    human_authorization_required: false,
    state: 'CURRENT',
    status: 'ACTIVE'
  }, {
    id: 'm5',
    protocol_version: '1.0',
    rule_key: 'HUMAN_IN_LOOP',
    priority: 5,
    instruction: 'Critical promotions and irreversible actions require explicit human authorization.',
    applies_to: 'ALL',
    authority_scope: 'SYSTEM',
    human_authorization_required: true,
    state: 'CURRENT',
    status: 'ACTIVE'
  }],
  llmRoutingRules: [{
    id: 'r1',
    task_domain: 'CODE',
    primary_platform: 'GROK',
    fallback_platforms: ['CLAUDE'],
    routing_reason: 'Verified callable + tool access',
    approval_required: 